syntax = "proto3";

package webauthn;

import "webauthn/login.proto";
import "webauthn/register.proto";

// Service handles WebAuthn/Passkey identity verification
service Service {
  // Begin the webauthn registration ceremony
  rpc BeginRegister(BeginRegisterRequest) returns (BeginRegisterResponse);
  // Finish the webauthn registration ceremony
  rpc FinishRegister(FinishRegisterRequest) returns (FinishRegisterResponse);

  // Begin the webauthn login ceremony
  rpc BeginLogin(BeginLoginRequest) returns (BeginLoginResponse);
  // Finish the webauthn login ceremony
  rpc FinishLogin(FinishLoginRequest) returns (FinishLoginResponse);
}
